-- Enable the pg_trgm extension for text search
create extension if not exists pg_trgm;

-- Create profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create documents table
create table documents (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  file_type text,
  uploaded_by uuid references auth.users not null,
  uploaded_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create chat_messages table
create table chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  message text not null,
  response text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table documents enable row level security;
alter table chat_messages enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Policies for documents
-- Admins can do everything, regular users can only view (for RAG context, though strictly speaking RAG might run server-side or with service role, 
-- but for this client-side demo, users need read access to documents to search them).
-- Actually, for security, maybe we should only allow admins to insert/delete, and everyone to read.

create policy "Documents are viewable by everyone."
  on documents for select
  using ( true );

create policy "Only admins can insert documents."
  on documents for insert
  with check ( 
    exists ( select 1 from profiles where id = auth.uid() and is_admin = true )
  );

create policy "Only admins can delete documents."
  on documents for delete
  using (
    exists ( select 1 from profiles where id = auth.uid() and is_admin = true )
  );

-- Policies for chat_messages
create policy "Users can view their own messages."
  on chat_messages for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own messages."
  on chat_messages for insert
  with check ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, is_admin)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', false);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
